paths:
  /products:
    get:
      tags: [Products]
      summary: Lista todos os produtos
      operationId: listProducts
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Product'

    post:
      tags: [Products]
      summary: Cria um novo produto (com upload de imagem)
      operationId: createProduct
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [name, price, photo]
              properties:
                name:
                  type: string
                  example: "Camiseta Azul"
                price:
                  type: number
                  format: float
                  example: 49.90
                photo:
                  type: string
                  format: binary
      responses:
        '201':
          description: Produto criado
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Product'
        '422':
          description: Erro de validação
